<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data.Exploration.Project.ECON.4110</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Data.Exploration.Project.ECON4110_files/libs/clipboard/clipboard.min.js"></script>
<script src="Data.Exploration.Project.ECON4110_files/libs/quarto-html/quarto.js"></script>
<script src="Data.Exploration.Project.ECON4110_files/libs/quarto-html/popper.min.js"></script>
<script src="Data.Exploration.Project.ECON4110_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Data.Exploration.Project.ECON4110_files/libs/quarto-html/anchor.min.js"></script>
<link href="Data.Exploration.Project.ECON4110_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Data.Exploration.Project.ECON4110_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Data.Exploration.Project.ECON4110_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Data.Exploration.Project.ECON4110_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Data.Exploration.Project.ECON4110_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data.Exploration.Project.ECON.4110</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="econ-4110-data-exploration-project-deadline-5.14.23" class="level1">
<h1><code>ECON 4110 : Data Exploration Project Deadline : 5.14.23</code></h1>
</section>
<section id="research-questionamong-colleges-that-predominantly-grant-bachelors-degrees-did-the-release-of-the-scorecard-shift-student-interest-to-high-earnings-colleges-relative-to-low-earnings-ones-as-proxied-by-google-searches-for-keywords-associated-with-those-colleges" class="level1">
<h1><strong><code>Research Question:</code></strong><code>Among colleges that predominantly grant bachelor’s degrees, did the release of the Scorecard shift student interest to high-earnings colleges relative to low-earnings ones (as proxied by Google searches for keywords associated with those colleges)?</code></h1>
</section>
<section id="import-clean-and-join-relevant-data" class="level1">
<h1><strong><code>1) Import, Clean, and Join Relevant Data</code></strong></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set wd</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># load relevant packages. </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.2     ✔ readr   2.1.4
✔ forcats 1.0.0     ✔ tibble  3.2.1
✔ ggplot2 3.4.2     ✔ tidyr   1.3.0
✔ purrr   1.0.1     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vtable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: kableExtra

Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create list of files after setting wd to Rawdata.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">pattern =</span> <span class="st">'trends_up_to'</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use import_list to compile the list of files into a dataset.</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">import_list</span>(files, <span class="at">rbind =</span> <span class="cn">TRUE</span>, <span class="at">fill =</span> <span class="cn">TRUE</span>)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert data to date format and aggregate by month. </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">week =</span> <span class="fu">str_sub</span>(monthorweek, <span class="at">start =</span> <span class="dv">1</span>, <span class="at">end =</span> <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">week =</span> <span class="fu">ymd</span>(week)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">floor_date</span>(week,<span class="st">"month"</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate by schname and keyword and standardize the index varaible.</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(schname, keyword) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index.standard =</span> ((index<span class="sc">-</span><span class="fu">mean</span>(index))<span class="sc">/</span><span class="fu">sd</span>(index)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use import() to read in scorecard data.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Scorecard <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">'Most+Recent+Cohorts+(Scorecard+Elements).csv'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Use names()[] to change the UNITID and OPEID column names to lower case. </span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(Scorecard)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"unitid"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(Scorecard)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"opeid"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#use import() to read in the id_name_link.csv file</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>id_name_link <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">'id_name_link.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge in the Scorecard Data. </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Use group_by() and mutate(n = n()) to count how many times each school name pops up in id_name_link.</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>      <span class="co"># mutate(n = n()) creates a new variable, n, in the data frame that represents the number of rows in each group.</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Then, filter() to get rid of any school names that show up more than once.</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(id_name_link, schname) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">schname_count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(schname_count <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,523 × 4
# Groups:   schname [3,523]
   unitid   opeid schname                                    schname_count
    &lt;int&gt;   &lt;int&gt; &lt;chr&gt;                                              &lt;int&gt;
 1 180203 2517500 aaniiih nakoda college                                 1
 2 222178  353700 abilene christian university                           1
 3 138558  154100 abraham baldwin agricultural college                   1
 4 172866 2050300 academy college                                        1
 5 412173 3346300 academy for nursing and health occupations             1
 6 108232  753100 academy of art university                              1
 7 475635 4185500 academy of couture art                                 1
 8 126182  134500 adams state university                                 1
 9 188429  266600 adelphi university                                     1
10 188438  286000 adirondack community college                           1
# ℹ 3,513 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the "schname" variable to link up the Google trends data (data) to id_name_link. </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use the "unitid" or "opeid" columns to link THAT to the Scorecard data. </span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># inner_join() can perform both of these links. </span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>data_JOIN_id_name_link_BY_schname <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data, id_name_link, <span class="at">by =</span> <span class="st">'schname'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(data, id_name_link, by = "schname"): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 2854 of `x` matches multiple rows in `y`.
ℹ Row 3591 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Scorecard_JOIN_data_AND_id_name_link_BY_unitid <span class="ot">&lt;-</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(data_JOIN_id_name_link_BY_schname, Scorecard, <span class="at">by =</span> <span class="st">"unitid"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>Scorecard_JOIN_data_AND_id_name_link_BY_unitid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,617,730 × 133
# Groups:   schname, keyword [9,914]
   schid schname  keyword keynum monthorweek index `_file` week       month     
   &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;   &lt;date&gt;     &lt;date&gt;    
 1 0     young h… young …      1 2013-03-31…    34 ./tren… 2013-03-31 2013-03-01
 2 0     young h… young …      1 2013-04-07…    36 ./tren… 2013-04-07 2013-04-01
 3 0     young h… young …      1 2013-04-14…    45 ./tren… 2013-04-14 2013-04-01
 4 0     young h… young …      1 2013-04-21…    45 ./tren… 2013-04-21 2013-04-01
 5 0     young h… young …      1 2013-04-28…   100 ./tren… 2013-04-28 2013-04-01
 6 0     young h… young …      1 2013-05-05…    42 ./tren… 2013-05-05 2013-05-01
 7 0     young h… young …      1 2013-05-12…    38 ./tren… 2013-05-12 2013-05-01
 8 0     young h… young …      1 2013-05-19…    38 ./tren… 2013-05-19 2013-05-01
 9 0     young h… young …      1 2013-05-26…    33 ./tren… 2013-05-26 2013-05-01
10 0     young h… young …      1 2013-06-02…    40 ./tren… 2013-06-02 2013-06-01
# ℹ 1,617,720 more rows
# ℹ 124 more variables: index.standard &lt;dbl&gt;, unitid &lt;int&gt;, opeid.x &lt;int&gt;,
#   opeid.y &lt;int&gt;, opeid6 &lt;int&gt;, INSTNM &lt;chr&gt;, CITY &lt;chr&gt;, STABBR &lt;chr&gt;,
#   INSTURL &lt;chr&gt;, NPCURL &lt;chr&gt;, HCM2 &lt;int&gt;, PREDDEG &lt;int&gt;, CONTROL &lt;int&gt;,
#   LOCALE &lt;chr&gt;, HBCU &lt;chr&gt;, PBI &lt;chr&gt;, ANNHI &lt;chr&gt;, TRIBAL &lt;chr&gt;,
#   AANAPII &lt;chr&gt;, HSI &lt;chr&gt;, NANTI &lt;chr&gt;, MENONLY &lt;chr&gt;, WOMENONLY &lt;chr&gt;,
#   RELAFFIL &lt;chr&gt;, SATVR25 &lt;chr&gt;, SATVR75 &lt;chr&gt;, SATMT25 &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="modify-data-for-regression" class="level1">
<h1><code>2) Modify Data for Regression</code></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for Bachelor Degree Universities using the variable name PREDDEG and set it to 3. </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>Scorecard_JOIN_data_AND_id_name_link_BY_unitid <span class="ot">&lt;-</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Scorecard_JOIN_data_AND_id_name_link_BY_unitid, PREDDEG <span class="sc">==</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define high, average, low income</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>income.mean <span class="ot">&lt;-</span> Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span><span class="st">`</span><span class="at">md_earn_wne_p10-REPORTED-EARNINGS</span><span class="st">`</span> <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  as.numeric <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()<span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in na.omit(.): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>income.sd <span class="ot">&lt;-</span> Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span><span class="st">`</span><span class="at">md_earn_wne_p10-REPORTED-EARNINGS</span><span class="st">`</span> <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in na.omit(.): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>income.high <span class="ot">&lt;-</span> income.mean<span class="sc">+</span>income.sd</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>income.low <span class="ot">&lt;-</span> income.mean<span class="sc">-</span>income.sd</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(income.low, income.mean, income.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  income.low income.mean income.high
       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1     31843.      43449.      55055.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define and clean variables of interest</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>income <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span><span class="st">`</span><span class="at">md_earn_wne_p10-REPORTED-EARNINGS</span><span class="st">`</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>schname <span class="ot">&lt;-</span> Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span>schname</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span>index.standard)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Date.bymonth <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(Scorecard_JOIN_data_AND_id_name_link_BY_unitid<span class="sc">$</span>month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-regression-data-frame" class="level1">
<h1><code>3) Create Regression Data Frame</code></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New df with only variables of interest</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>Plot.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Date.bymonth =</span> Date.bymonth,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">University.Name =</span> schname,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">University.Mean.Income =</span> income,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">University.Interest =</span> index</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># eliminate rows with NA values (privacy protected)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>Plot.df <span class="ot">&lt;-</span> Plot.df <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(University.Mean.Income) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(University.Interest))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date of Scorecard Introduction : 2015-09</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column "Scorecard.pre.post" based on the date condition</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>Plot.df <span class="ot">&lt;-</span> Plot.df <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Scorecard.pre.post =</span> <span class="fu">case_when</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    Date.bymonth <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2015-09-12"</span>) <span class="sc">~</span> <span class="st">"Before"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    Date.bymonth <span class="sc">&gt;</span> <span class="fu">as.Date</span>(<span class="st">"2015-09-12"</span>) <span class="sc">~</span> <span class="st">"After"</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a set of variables that are 'High'  if the school is high income, 'Low' if low income, and 'Medium' if in the middle.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># neither high nor Low income, and 'Low' if the school is low income.</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>Plot.df <span class="ot">&lt;-</span> Plot.df <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">University.Income.Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    University.Mean.Income <span class="sc">&gt;=</span> income.high <span class="sc">~</span> <span class="st">'High'</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    University.Mean.Income <span class="sc">&gt;=</span> income.low <span class="sc">~</span> <span class="st">'Medium'</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    University.Mean.Income <span class="sc">&lt;=</span> income.low <span class="sc">~</span> <span class="st">'Low'</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize mean interest over time per group. Save to new data frame to be used for OLS Regression. </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Plot.df2 <span class="ot">&lt;-</span> Plot.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Date.bymonth, University.Income.Category) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Group.Mean.Interest =</span> <span class="fu">mean</span>(University.Interest)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Date.bymonth'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date of Scorecard Introduction : 2015-09</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column "Scorecard.pre.post" based on the date condition</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>Plot.df2 <span class="ot">&lt;-</span> Plot.df2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Scorecard.pre.post =</span> <span class="fu">case_when</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    Date.bymonth <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2015-09-12"</span>) <span class="sc">~</span> <span class="st">"Before"</span> ,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    Date.bymonth <span class="sc">&gt;</span> <span class="fu">as.Date</span>(<span class="st">"2015-09-12"</span>) <span class="sc">~</span> <span class="st">"After"</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-data" class="level1">
<h1><code>4) Plot Data</code></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot data</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#gg point plot</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>Plot.point <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Plot.df2, <span class="fu">aes</span>(<span class="at">x =</span> Date.bymonth, <span class="at">y =</span> Group.Mean.Interest, <span class="at">color =</span> University.Income.Category)) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">ymd</span>(<span class="st">'2015-09-12'</span>))</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>Plot.point</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Data.Exploration.Project.ECON4110_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gg point and line plot</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>Plot.line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Plot.df2, <span class="fu">aes</span>(<span class="at">x =</span> Date.bymonth, <span class="at">y =</span> Group.Mean.Interest, <span class="at">color =</span> University.Income.Category)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">as.Date</span>(<span class="st">'2015-09-12'</span>), <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Standardized Google Trends Index for Bachelor-Focused Universities by Income Category'</span>, <span class="at">x =</span> <span class="st">'Date'</span>, <span class="at">y =</span> <span class="st">'Interest'</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>Plot.line</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Data.Exploration.Project.ECON4110_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="run-regression" class="level1">
<h1><code>6) Run Regression</code></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS Regression</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># regress index on scorecard. </span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>OLS.Reg.Plot.df2 <span class="ot">&lt;-</span> Plot.df2 <span class="sc">%&gt;%</span> <span class="fu">feols</span>(Group.Mean.Interest <span class="sc">~</span> <span class="fu">i</span>(Scorecard.pre.post, <span class="at">ref =</span> <span class="st">'Before'</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(OLS.Reg.Plot.df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              OLS.Reg.Plot.df2
Dependent Var.:            Group.Mean.Interest
                                              
Constant                       0.0525 (0.0379)
Scorecard.pre.post = After  -0.2495** (0.0942)
__________________________ ___________________
S.E. type                                  IID
Observations                               111
R2                                     0.06049
Adj. R2                                0.05187
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Control for time, and Income Category</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>OLS.Reg.Plot.df2 <span class="ot">&lt;-</span> Plot.df2 <span class="sc">%&gt;%</span> <span class="fu">feols</span>(Group.Mean.Interest <span class="sc">~</span> <span class="fu">i</span>(Scorecard.pre.post, <span class="at">ref =</span> <span class="st">'Before'</span>)<span class="sc">*</span>Date.bymonth <span class="sc">+</span> <span class="fu">i</span>(University.Income.Category, <span class="at">ref =</span> <span class="st">'Medium'</span>))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(OLS.Reg.Plot.df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                     OLS.Reg.Plot.df2
Dependent Var.:                                   Group.Mean.Interest
                                                                     
Constant                                             9.981*** (2.083)
i(factor_var=Scorecard.pre.post,ref="Before")           12.16 (25.68)
Date.bymonth                                      -0.0006*** (0.0001)
University.Income.Category = High                     0.0031 (0.0783)
University.Income.Category = Low                     -0.0092 (0.0783)
Date.bymonth x i(Scorecard.pre.post,ref="Before")    -0.0007 (0.0015)
________________________________________          ___________________
S.E. type                                                         IID
Observations                                                      111
R2                                                            0.23246
Adj. R2                                                       0.19591
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpret-regression-and-conclude" class="level1">
<h1><code>Interpret Regression and Conclude</code></h1>
<p>This regression model aims to explain the relationship between the dependent variable “Group.Mean.Interest” and several independent variables.</p>
<p><u>Coefficient Interpretation:</u></p>
<p><strong>Beta 0:</strong> The estimated intercept of the regression equation is 9.981. This means that when all other independent variables are zero, the expected value of “Group.Mean.Interest” is 9.981.</p>
<p><strong>Beta 1:</strong> i(factor_var=Scorecard.pre.post, ref=“Before”): This variable represents the effect of the factor variable “Scorecard.pre.post” with a reference level of “Before”. The coefficient estimate is 12.16, but it is not statistically significant at conventional levels (p-value &gt; 0.05). This suggests that there is no significant difference in “Group.Mean.Interest” between the “Before” and “After” levels of the “Scorecard.pre.post” variable.</p>
<p><strong>Beta 2:</strong> Date.bymonth: The coefficient estimate is -0.0006, and it is statistically significant (p-value &lt; 0.001). This suggests that as the “Date.bymonth” variable increases by one unit, “Group.Mean.Interest” decreases by 0.0006 units.</p>
<p><strong>Beta 3:</strong> University.Income.Category = High: This variable represents the effect of the “University.Income.Category” variable when it takes the value “High”. The coefficient estimate is 0.0031, but it is not statistically significant (p-value &gt; 0.05). This suggests that there is no significant difference in “Group.Mean.Interest” between the “High” and “Low” levels of the “University.Income.Category” variable.</p>
<p><strong>Beta 4:</strong> University.Income.Category = Low: This variable represents the effect of the “University.Income.Category” variable when it takes the value “Low”. The coefficient estimate is -0.0092, but it is not statistically significant (p-value &gt; 0.05). This suggests that there is no significant difference in “Group.Mean.Interest” between the “High” and “Low” levels of the “University.Income.Category” variable.</p>
<p><strong>Beta 5:</strong> Date.bymonth*i(Scorecard.pre.post, ref=“Before”): This variable represents the interaction effect between “Date.bymonth” and the factor variable “Scorecard.pre.post” with a reference level of “Before”. The coefficient estimate is -0.0007, but it is not statistically significant (p-value &gt; 0.05). This suggests that there is no significant interaction effect between “Date.bymonth” and “Scorecard.pre.post” on “Group.Mean.Interest”.</p>
<p><strong>R Square:</strong> The R-squared value of 0.23246 indicates that the independent variables in the model explain approximately 23.2% of the variation in the dependent variable. The adjusted R-squared value of 0.19591 accounts for the degrees of freedom and provides a more accurate measure of model fit. Note that it is lower than the unadjusted value.</p>
<p>R-Square is not especially relevant in this analysis, however.</p>
<p>The model suggests that the “Date.bymonth” variable has a significant negative effect on “Group.Mean.Interest”. Time is the only variable that has a statistically significant effect on Group.Mean.Interest.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>